discovery:
  version: v1 
  address: localhost:8080
  db:
    - 0.0.0.0:2379
  heartbeat: 0.0.0.0:4222
  heartbeatTopic: /heartbeat/
  instrument:
    address: 0.0.0.0:4222
    stopic: collector
    collect: 15s
    location: logs/
